### ISSUE TITLE
[5]low prioritization ecxeption is thrown in server when user quits forcely 

### ISSUE THREAD

**Issue by Gamefors** [Gamefors/Python#11]
## Description:
ecxeption is thrown in server when user quits forcely
## Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gamef\Documents\GitHub\Python\server\utils\connectionuser.py", line 50, in listen
    if "*start_server_request~" in data:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Gamefors** [comment]
bug is not logged to server log so it is not an normal prioritization bug

**Comment by Gamefors** [comment]
maybe fixed bc there is now thrown exception when user quits
